'use client'

import { SessionProvider } from 'next-auth/react'
import '../styles/globals.css'
import { StoreProvider } from '../utils/Store'
import Footer from './components/Footer'
import Header from './components/Header'
import { ToastContainer } from 'react-toastify'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <StoreProvider>
        <body>
          <SessionProvider>
            <div className='flex min-h-screen flex-col justify-between'>
              <Header />
              {children}
              <Footer />
            </div>
          </SessionProvider>
        </body>
      </StoreProvider>
    </html>
  )
}
